CREATE TABLE owners(
   id                    INTEGER  NOT NULL PRIMARY KEY,
  first_name            VARCHAR(10) NOT NULL,
  last_name             VARCHAR(11) NOT NULL,
  full_name             VARCHAR(26) NOT NULL,
  job_title             VARCHAR(40) NOT NULL,
  job_type              VARCHAR(13) NOT NULL,
  phone                 VARCHAR(21) NOT NULL,
  email                 VARCHAR(32) NOT NULL,
  image                 VARCHAR(58) NOT NULL,
  country               VARCHAR(15) NOT NULL,
  city                  VARCHAR(18) NOT NULL,
  onboarding_completion INTEGER  NOT NULL
);

INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (0,'Marilyne','Haag','Ms. Jesse Reinger','Investor Intranet Manager','National','582-730-9554','Ludwig.Schinner@hotmail.com','https://cdn.fakercloud.com/avatars/ashernatali_128.jpg','Borders','Port Manleymouth',59);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (1,'Westley','Waters','Jack Mohr','Dynamic Brand Technician','Dynamic','(488) 804-9935','Ken70@hotmail.com','https://cdn.fakercloud.com/avatars/logorado_128.jpg','Avon','Seamuschester',40);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (2,'Madalyn','Stehr','Lorena Leannon','Regional Identity Analyst','Dynamic','(495) 972-9299 x540','Izabella.Hintz@yahoo.com','https://cdn.fakercloud.com/avatars/artd_sign_128.jpg','Bedfordshire','Lombard',60);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (3,'Gloria','White','Maggie Prosacco','Direct Integration Administrator','Central','695.863.1061 x666','Viva_Weimann@gmail.com','https://cdn.fakercloud.com/avatars/kaysix_dizzy_128.jpg','Berkshire','New Darrel',47);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (4,'Loy','Lubowitz','Betty Hills PhD','Product Paradigm Technician','Principal','945.768.2077 x62117','Madeline77@gmail.com','https://cdn.fakercloud.com/avatars/joeymurdah_128.jpg','Bedfordshire','Medford',59);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (5,'Christophe','Kub','Mae Paucek','Central Research Engineer','Forward','263-303-1860 x3477','Johnathon.Kerluke57@gmail.com','https://cdn.fakercloud.com/avatars/leonfedotov_128.jpg','Borders','Hendersonfurt',24);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (6,'Glenna','Murray','Delia Gusikowski Jr.','Customer Solutions Specialist','Legacy','411.792.8720','Reta81@gmail.com','https://cdn.fakercloud.com/avatars/holdenweb_128.jpg','Bedfordshire','Murphybury',3);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (7,'Adan','Schulist','Annette Nader','Investor Solutions Engineer','Dynamic','709.417.1730 x02729','Dusty16@hotmail.com','https://cdn.fakercloud.com/avatars/gauchomatt_128.jpg','Avon','Round Rock',16);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (8,'Thea','Rempel','Leland Keebler','Forward Identity Engineer','International','513-231-3585 x46288','Jayce_Huels10@gmail.com','https://cdn.fakercloud.com/avatars/oktayelipek_128.jpg','Cambridgeshire','Antioch',9);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (9,'Domenic','Lubowitz','Omar Collins','Direct Response Representative','Product','1-660-937-7509','Guadalupe.Ortiz28@hotmail.com','https://cdn.fakercloud.com/avatars/jerrybai1907_128.jpg','Bedfordshire','Percyville',99);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (10,'Ericka','Ziemann','Erin Torphy','Human Tactics Engineer','Internal','675-698-1402 x90055','Evan72@gmail.com','https://cdn.fakercloud.com/avatars/gcmorley_128.jpg','Buckinghamshire','Tatummouth',19);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (11,'Joshuah','Greenholt','Darla Mosciski','Direct Response Assistant','Central','390.604.0925','Norris_Haag15@gmail.com','https://cdn.fakercloud.com/avatars/homka_128.jpg','Borders','Lorenzostad',65);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (12,'Johnathon','Rogahn','Mildred Ziemann','National Brand Administrator','Dynamic','(551) 235-1755','Donnell98@yahoo.com','https://cdn.fakercloud.com/avatars/baluli_128.jpg','Avon','Eloisebury',61);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (13,'Amy','Murphy','Ms. Donna Mitchell','Internal Usability Associate','Product','512.590.9251 x378','Kane_Bosco@gmail.com','https://cdn.fakercloud.com/avatars/dmackerman_128.jpg','Buckinghamshire','East Micahfort',75);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (14,'Fabian','Carroll','Ramona Crona','Human Group Designer','Dynamic','(714) 337-4164 x441','Isaac.Schamberger8@hotmail.com','https://cdn.fakercloud.com/avatars/jeremiespoken_128.jpg','Bedfordshire','New Thomashaven',66);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (15,'Allene','Quigley','Dr. Shane Tillman','District Web Strategist','International','(485) 360-9707 x61121','Donald36@yahoo.com','https://cdn.fakercloud.com/avatars/kapaluccio_128.jpg','Avon','Port Joanneborough',18);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (16,'Myrtice','Ferry','Kristen Ortiz','Corporate Metrics Manager','Forward','1-228-755-7346','Rusty64@hotmail.com','https://cdn.fakercloud.com/avatars/kkusaa_128.jpg','Bedfordshire','North Carsonbury',39);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (17,'Kiara','Jenkins','Scott Kirlin','Corporate Factors Officer','Product','844.433.3960','Lisandro.Lubowitz49@gmail.com','https://cdn.fakercloud.com/avatars/eddiechen_128.jpg','Bedfordshire','New Rosa',38);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (18,'Katlyn','Corwin','Homer Collier','Dynamic Optimization Assistant','Future','1-647-972-2036','Kenna_Abshire64@yahoo.com','https://cdn.fakercloud.com/avatars/gonzalorobaina_128.jpg','Berkshire','Haagburgh',55);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (19,'Patience','Huel','Lucille Stehr','Legacy Accounts Manager','Global','1-657-773-5767 x6948','Ron.Langworth99@gmail.com','https://cdn.fakercloud.com/avatars/bu7921_128.jpg','Berkshire','Kristoferstad',85);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (20,'Tomasa','Gibson','Henry Hane','Product Metrics Coordinator','Global','244.971.7614','Martin_Marvin@yahoo.com','https://cdn.fakercloud.com/avatars/iduuck_128.jpg','Berkshire','Eileenshire',50);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (21,'Alexander','Waelchi','Dennis Nicolas','Global Assurance Officer','Principal','1-948-714-5709 x569','Dayana_Rau75@gmail.com','https://cdn.fakercloud.com/avatars/denisepires_128.jpg','Avon','Peoria',27);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (22,'Geo','Mertz','Earnest Leffler','Dynamic Security Facilitator','Human','282.751.2181','Dorthy.Gorczany@hotmail.com','https://cdn.fakercloud.com/avatars/kurtinc_128.jpg','Bedfordshire','West Jocelyn',77);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (23,'Mateo','Price','Thelma Glover','Global Metrics Liaison','Dynamic','788-664-2477','Jaqueline95@yahoo.com','https://cdn.fakercloud.com/avatars/gauravjassal_128.jpg','Cambridgeshire','Josephinemouth',12);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (24,'Saul','Cole','Bradley Stamm','Customer Communications Executive','Product','1-832-988-8079 x80159','Francesco.Trantow25@gmail.com','https://cdn.fakercloud.com/avatars/leeiio_128.jpg','Borders','Yundtton',28);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (25,'Carroll','Rath','Winston Legros','Legacy Brand Consultant','Global','260-898-9279 x71605','Lucienne.Cronin27@gmail.com','https://cdn.fakercloud.com/avatars/ninjad3m0_128.jpg','Avon','West Eino',73);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (26,'Elise','Hahn','Eugene Haag','Future Integration Designer','Corporate','649-779-0478 x2271','Kaci.Lind@yahoo.com','https://cdn.fakercloud.com/avatars/tjrus_128.jpg','Borders','Darrickland',4);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (27,'Clemmie','Collins','Josh Schinner','Central Response Technician','Customer','487-345-0160','Kitty35@hotmail.com','https://cdn.fakercloud.com/avatars/trubeatto_128.jpg','Cambridgeshire','Morissetteview',4);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (28,'Delphine','Marks','Mrs. Ada Goyette','Global Group Consultant','Regional','1-512-859-4640','Evangeline_Douglas59@yahoo.com','https://cdn.fakercloud.com/avatars/iamgarth_128.jpg','Borders','South Effie',44);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (29,'Adalberto','Hayes','Phyllis Klocko III','Global Response Planner','District','211.813.9196','Julien.Hodkiewicz@yahoo.com','https://cdn.fakercloud.com/avatars/brandonburke_128.jpg','Bedfordshire','Franeckimouth',85);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (30,'Marcia','Pollich','Omar Blick','Investor Response Liaison','Dynamic','(451) 987-4292 x49261','Rhett.Rath33@yahoo.com','https://cdn.fakercloud.com/avatars/pixage_128.jpg','Buckinghamshire','Petaluma',78);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (31,'Bryon','Leannon','Ms. Carl Wintheiser','Dynamic Accountability Officer','National','465-411-0136 x9074','Dorothea64@gmail.com','https://cdn.fakercloud.com/avatars/emileboudeling_128.jpg','Buckinghamshire','Langworthberg',9);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (32,'Devyn','Bradtke','Wanda Lemke','International Communications Coordinator','Future','(930) 987-7692 x34090','Jayme_OKon@gmail.com','https://cdn.fakercloud.com/avatars/terpimost_128.jpg','Berkshire','Port Arnulfo',27);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (33,'Hilda','Padberg','Eunice Wolf','Lead Communications Planner','Senior','1-698-748-9031 x22014','Lafayette_Willms@hotmail.com','https://cdn.fakercloud.com/avatars/oktayelipek_128.jpg','Berkshire','Marlinstad',33);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (34,'Josephine','Lubowitz','Donald Beier','Principal Interactions Specialist','Dynamic','1-282-688-4232','Ofelia84@gmail.com','https://cdn.fakercloud.com/avatars/dpmachado_128.jpg','Bedfordshire','Botsfordberg',6);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (35,'Kenna','Swaniawski','Miss Taylor Rice','Direct Branding Director','National','480-972-8786','Kory_Bailey38@gmail.com','https://cdn.fakercloud.com/avatars/brunodesign1206_128.jpg','Buckinghamshire','East Modestoberg',5);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (36,'Tony','Wuckert','Kristine Schultz','Chief Metrics Engineer','Direct','(491) 811-5739','Laron_Veum@hotmail.com','https://cdn.fakercloud.com/avatars/larrygerard_128.jpg','Buckinghamshire','Stammstad',20);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (37,'Billy','Keeling','Duane Hessel','Internal Accountability Planner','Senior','1-679-865-9481','Missouri99@yahoo.com','https://cdn.fakercloud.com/avatars/pifagor_128.jpg','Borders','Kulasmouth',3);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (38,'Hazel','Murphy','Lora Fritsch','Investor Implementation Manager','International','1-923-250-7342','Sabrina13@hotmail.com','https://cdn.fakercloud.com/avatars/megdraws_128.jpg','Borders','Lake Rettaview',43);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (39,'Anika','Zboncak','Dr. Francis Mitchell','Principal Research Designer','Customer','1-499-231-7543 x9506','Vivienne_Roberts33@yahoo.com','https://cdn.fakercloud.com/avatars/kuldarkalvik_128.jpg','Berkshire','Bartlett',81);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (40,'Jules','Nader','Victor Kreiger','Central Accounts Designer','Direct','878.372.3045 x2128','Lester76@yahoo.com','https://cdn.fakercloud.com/avatars/lhausermann_128.jpg','Berkshire','Concepcionport',85);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (41,'Erwin','Halvorson','Mr. Ronald O''Kon','Product Metrics Architect','Internal','(944) 461-5093','Eulah.Maggio44@yahoo.com','https://cdn.fakercloud.com/avatars/smenov_128.jpg','Avon','Stiedemannborough',46);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (42,'Jarvis','Schuppe','Stephanie Heathcote','Corporate Creative Supervisor','Corporate','(560) 910-0072 x3161','Emilia.Leannon@hotmail.com','https://cdn.fakercloud.com/avatars/pehamondello_128.jpg','Cambridgeshire','West Ivaville',5);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (43,'Talon','Lubowitz','Miss Casey Weissnat','Corporate Assurance Planner','Direct','206.767.7700 x30572','Levi_Mann66@gmail.com','https://cdn.fakercloud.com/avatars/a1chapone_128.jpg','Cambridgeshire','Mariannehaven',82);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (44,'Warren','Hauck','Lora Pacocha','Dynamic Directives Analyst','Corporate','672-343-4078 x103','Joe_Rippin49@yahoo.com','https://cdn.fakercloud.com/avatars/marrimo_128.jpg','Berkshire','Surprise',69);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (45,'Kennedy','Waters','Rafael Fritsch','Internal Program Architect','Dynamic','829.537.4315 x92261','Grady5@yahoo.com','https://cdn.fakercloud.com/avatars/jagan123_128.jpg','Cambridgeshire','East Aiyanafort',90);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (46,'Shanie','Schinner','Inez Heaney','Principal Branding Strategist','Investor','570.652.0161 x6679','Olin_Dibbert@gmail.com','https://cdn.fakercloud.com/avatars/oscarowusu_128.jpg','Avon','Lednerview',82);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (47,'Ola','Stamm','Janis Roob','Principal Configuration Facilitator','District','395-744-3845','Meaghan_Kunze93@hotmail.com','https://cdn.fakercloud.com/avatars/victorquinn_128.jpg','Bedfordshire','Baileybury',100);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (48,'Trevion','Roberts','Alicia Powlowski','Chief Infrastructure Technician','Dynamic','511-942-8230','Rachelle_Muller@hotmail.com','https://cdn.fakercloud.com/avatars/n_tassone_128.jpg','Bedfordshire','South Major',86);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (49,'Gregory','Stehr','Casey Kulas','Customer Research Associate','Future','1-871-534-6466 x661','Olga.Rodriguez@yahoo.com','https://cdn.fakercloud.com/avatars/scips_128.jpg','Cambridgeshire','Port Myrtisborough',38);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (50,'Esta','Larson','Dr. Lana Bins','Product Intranet Engineer','Principal','1-502-292-5649','Hans.Stanton@hotmail.com','https://cdn.fakercloud.com/avatars/gaborenton_128.jpg','Cambridgeshire','New Garrytown',18);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (51,'Linnie','Murphy','Chelsea Kozey','Principal Usability Liaison','Investor','284-766-9076 x78268','Dario_Herman@gmail.com','https://cdn.fakercloud.com/avatars/mgonto_128.jpg','Cambridgeshire','Wilkinsonville',23);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (52,'Luna','Kuphal','Blanca Oberbrunner','Corporate Marketing Assistant','District','358-977-9727','Daphne_Leannon@gmail.com','https://cdn.fakercloud.com/avatars/rikas_128.jpg','Borders','Dickinsontown',27);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (53,'Columbus','Von','Jessica Davis DDS','Central Paradigm Liaison','Dynamic','872.567.0744 x639','Pedro_Kuhn@yahoo.com','https://cdn.fakercloud.com/avatars/svenlen_128.jpg','Borders','Bergstromport',50);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (54,'Keagan','Harber','Lynette Cremin','Internal Factors Representative','District','1-438-364-9403','Adrain.Bergnaum@yahoo.com','https://cdn.fakercloud.com/avatars/aka_james_128.jpg','Buckinghamshire','North Lavernetown',12);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (55,'Clark','Schulist','Whitney Borer','Direct Interactions Executive','Human','493.444.1830','Henri.Carroll@hotmail.com','https://cdn.fakercloud.com/avatars/hasslunsford_128.jpg','Berkshire','Turcotteshire',97);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (56,'Era','Dooley','Rita Schaden','Investor Division Strategist','Corporate','331-790-5318 x686','Shirley79@gmail.com','https://cdn.fakercloud.com/avatars/johannesneu_128.jpg','Avon','Bedford',85);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (57,'Karlee','Mayer','Christine Quitzon','National Solutions Administrator','Regional','1-311-704-4724 x79193','Danial.Bode1@yahoo.com','https://cdn.fakercloud.com/avatars/holdenweb_128.jpg','Buckinghamshire','Port Rodrigoland',80);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (58,'Loy','Walsh','Alfonso Hackett','Lead Data Architect','Principal','(411) 710-6254','Wilfred_Emard31@hotmail.com','https://cdn.fakercloud.com/avatars/findingjenny_128.jpg','Avon','Tampa',92);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (59,'Antonetta','Champlin','Dr. Vernon Kohler','Dynamic Communications Officer','National','1-352-463-9063 x5983','Davion.OHara70@hotmail.com','https://cdn.fakercloud.com/avatars/salleedesign_128.jpg','Borders','Johnstonville',75);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (60,'Stephen','Kassulke','Mrs. Naomi Monahan','Human Markets Assistant','Regional','(518) 446-7647 x8950','Yasmeen.Spinka@gmail.com','https://cdn.fakercloud.com/avatars/raphaelnikson_128.jpg','Avon','New Jonathan',88);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (61,'Jalon','Kuhn','Dr. Tasha McLaughlin','Investor Paradigm Engineer','Global','1-667-262-6851','Colten56@gmail.com','https://cdn.fakercloud.com/avatars/jesseddy_128.jpg','Cambridgeshire','Lake Dayne',32);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (62,'Lyric','Ziemann','Hannah Steuber','National Security Strategist','Senior','(504) 468-0447','Alexzander_Strosin11@gmail.com','https://cdn.fakercloud.com/avatars/umurgdk_128.jpg','Borders','West Litzy',97);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (63,'Vivienne','Bogan','Melba Willms Jr.','Lead Creative Facilitator','Dynamic','947.589.1835 x6599','Rashad56@yahoo.com','https://cdn.fakercloud.com/avatars/ssiskind_128.jpg','Cambridgeshire','Meaghanchester',95);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (64,'Bella','Berge','Violet Bosco','Corporate Program Agent','Future','947-678-7614 x57474','Jules49@yahoo.com','https://cdn.fakercloud.com/avatars/mhesslow_128.jpg','Berkshire','New Tomasa',13);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (65,'Litzy','Kassulke','Miss Miriam Doyle','Dynamic Integration Producer','Lead','(968) 252-1275','Joyce.Kub27@yahoo.com','https://cdn.fakercloud.com/avatars/gu5taf_128.jpg','Buckinghamshire','Port Donaldmouth',75);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (66,'Jazmin','Green','Clarence Larkin','Lead Functionality Developer','Future','605-462-0835 x82498','Andreanne_Robel@hotmail.com','https://cdn.fakercloud.com/avatars/HenryHoffman_128.jpg','Buckinghamshire','Tallahassee',50);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (67,'Vicente','Watsica','Dr. Brent Welch','Regional Directives Supervisor','Global','(300) 766-9301 x9170','Winifred.Kerluke@gmail.com','https://cdn.fakercloud.com/avatars/sasha_shestakov_128.jpg','Borders','Lake Jailyn',72);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (68,'Eddie','Boyer','Caleb Abshire','Future Factors Officer','International','645.940.6618 x023','Carlie.Jakubowski78@yahoo.com','https://cdn.fakercloud.com/avatars/mattlat_128.jpg','Bedfordshire','Jeffereystad',15);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (69,'Ewald','Konopelski','Nancy Breitenberg','Internal Solutions Manager','Investor','1-280-653-5301 x773','Derek67@hotmail.com','https://cdn.fakercloud.com/avatars/logorado_128.jpg','Buckinghamshire','North Guy',95);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (70,'Keara','Kulas','Mrs. Margie Kihn','Direct Interactions Orchestrator','Human','206-514-8295 x921','Salvatore68@hotmail.com','https://cdn.fakercloud.com/avatars/gauravjassal_128.jpg','Buckinghamshire','New Cheyannemouth',53);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (71,'Cole','Lemke','Ruth Gutmann','Lead Branding Developer','Global','(226) 754-9553','Michael.Grady62@hotmail.com','https://cdn.fakercloud.com/avatars/themadray_128.jpg','Buckinghamshire','Rio Rancho',92);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (72,'Ignatius','Schuster','Victor Waters','Customer Functionality Administrator','Dynamic','1-602-963-4417','Gerhard15@hotmail.com','https://cdn.fakercloud.com/avatars/ostirbu_128.jpg','Borders','New Stefaniefurt',12);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (73,'Mae','Harvey','Melvin Lakin','Investor Identity Agent','Legacy','284-459-4107 x45533','Helga_Boehm@hotmail.com','https://cdn.fakercloud.com/avatars/homka_128.jpg','Buckinghamshire','Gaithersburg',59);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (74,'Candido','Frami','Louise Doyle DVM','Chief Functionality Architect','Principal','972.648.4162','Sandy28@yahoo.com','https://cdn.fakercloud.com/avatars/naitanamoreno_128.jpg','Bedfordshire','Lake Dawson',41);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (75,'Pink','Tromp','Domingo Langworth','Dynamic Applications Manager','Dynamic','1-958-297-0611','Michelle53@hotmail.com','https://cdn.fakercloud.com/avatars/kimcool_128.jpg','Cambridgeshire','Port Margieton',49);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (76,'Lorine','Bergnaum','Joey Donnelly','Product Optimization Supervisor','Forward','368.814.1818','Tomas_Medhurst@yahoo.com','https://cdn.fakercloud.com/avatars/terpimost_128.jpg','Bedfordshire','Daneland',43);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (77,'Rosalyn','Runte','Lloyd McDermott','Principal Accounts Analyst','Investor','958.418.8863 x064','Norris.Stanton12@yahoo.com','https://cdn.fakercloud.com/avatars/isnifer_128.jpg','Avon','East Orange',94);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (78,'Alycia','Boehm','Blanche Heidenreich','Central Assurance Technician','Legacy','1-345-956-4623','Clement.Anderson0@gmail.com','https://cdn.fakercloud.com/avatars/ManikRathee_128.jpg','Bedfordshire','Blicktown',15);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (79,'Victoria','Rath','Martin Marks','Central Brand Representative','Investor','1-434-880-7513','Jayce_Willms79@yahoo.com','https://cdn.fakercloud.com/avatars/opnsrce_128.jpg','Berkshire','New Bennettport',54);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (80,'Jeramy','Cremin','Dorothy Hahn','District Functionality Technician','Principal','606.739.6770','Mylene97@yahoo.com','https://cdn.fakercloud.com/avatars/calebogden_128.jpg','Avon','Dianahaven',32);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (81,'Claudie','Johnson','Hope Carroll','International Interactions Executive','Central','676.761.8406','Name40@gmail.com','https://cdn.fakercloud.com/avatars/levisan_128.jpg','Cambridgeshire','Port Catalinashire',59);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (82,'Marlene','Rath','Dr. Alexander West','Legacy Response Planner','Customer','(798) 413-1589 x60793','Alexandra_Metz80@yahoo.com','https://cdn.fakercloud.com/avatars/ariffsetiawan_128.jpg','Bedfordshire','North Lilla',18);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (83,'Lisette','Cruickshank','Angel Wilkinson','Regional Communications Assistant','Central','(550) 923-6245 x39127','Estel_Nienow15@gmail.com','https://cdn.fakercloud.com/avatars/mcflydesign_128.jpg','Borders','West Cole',63);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (84,'Neil','Bogisich','Faye McCullough','Regional Assurance Planner','Principal','952.937.3157','Jakob.Collins2@gmail.com','https://cdn.fakercloud.com/avatars/mugukamil_128.jpg','Cambridgeshire','East Arlie',8);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (85,'Haven','Stark','William Roberts','Chief Accounts Supervisor','Principal','344.295.0821 x445','Kraig.Hermann@yahoo.com','https://cdn.fakercloud.com/avatars/chacky14_128.jpg','Berkshire','Alicetown',4);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (86,'Donnell','Davis','Naomi Considine','Future Functionality Specialist','Forward','807.966.5306 x5818','Gaetano63@yahoo.com','https://cdn.fakercloud.com/avatars/michaelkoper_128.jpg','Cambridgeshire','North Jabarimouth',20);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (87,'Santos','Dickinson','Aubrey Gutkowski','Dynamic Implementation Planner','Regional','1-244-567-7367 x76384','Torrance_Aufderhar@yahoo.com','https://cdn.fakercloud.com/avatars/muringa_128.jpg','Avon','Estelmouth',25);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (88,'Judd','Gerhold','Rogelio Fay PhD','Corporate Tactics Strategist','Principal','1-444-230-8955','Montana92@hotmail.com','https://cdn.fakercloud.com/avatars/nicollerich_128.jpg','Avon','Kaylieville',9);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (89,'Giovanni','Feil','Anne Carter Sr.','District Accounts Consultant','Chief','487.224.1765 x622','Cleora6@yahoo.com','https://cdn.fakercloud.com/avatars/kikillo_128.jpg','Cambridgeshire','South Alberto',64);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (90,'Anna','Carroll','Ralph Conn','Global Factors Designer','Global','576-537-5271 x2699','Libby.Mueller@gmail.com','https://cdn.fakercloud.com/avatars/victor_haydin_128.jpg','Cambridgeshire','South Lanechester',47);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (91,'Vance','Mante','Terrence Effertz','Senior Interactions Representative','Forward','1-301-889-2870 x0171','Fleta_Rodriguez@yahoo.com','https://cdn.fakercloud.com/avatars/kaelifa_128.jpg','Cambridgeshire','Port Jillian',18);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (92,'Mustafa','Schaden','Katie Brown','Product Metrics Consultant','Corporate','(897) 590-8535','Asia_Ernser17@hotmail.com','https://cdn.fakercloud.com/avatars/markjenkins_128.jpg','Borders','Lindseyview',95);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (93,'Keenan','Heathcote','Ruby Ziemann','Dynamic Usability Analyst','Direct','1-223-246-6559 x75522','Chandler74@hotmail.com','https://cdn.fakercloud.com/avatars/byryan_128.jpg','Berkshire','Marietta',82);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (94,'Estel','Sawayn','Jackie Waters','Corporate Markets Technician','Internal','429-697-8589 x995','Abdiel_Schuppe@gmail.com','https://cdn.fakercloud.com/avatars/nateschulte_128.jpg','Buckinghamshire','Markburgh',62);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (95,'Benedict','O''Conner','Lois Miller','Principal Group Analyst','Internal','(212) 667-7618 x8211','Maxwell.Kozey@yahoo.com','https://cdn.fakercloud.com/avatars/anasnakawa_128.jpg','Cambridgeshire','Hahnburgh',73);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (96,'Jerod','Crona','Irving Zulauf','District Identity Supervisor','International','350-209-9708 x89106','Hector.Gislason83@hotmail.com','https://cdn.fakercloud.com/avatars/adellecharles_128.jpg','Berkshire','Ryanhaven',43);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (97,'Howard','Quitzon','Jasmine O''Conner','District Branding Manager','Legacy','941.825.3766','Khalil.Casper@yahoo.com','https://cdn.fakercloud.com/avatars/bboy1895_128.jpg','Berkshire','Greenfeldermouth',36);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (98,'Serenity','Sawayn','Stuart Skiles','District Security Architect','Dynamic','720.735.6852 x012','Bernice_Dibbert73@hotmail.com','https://cdn.fakercloud.com/avatars/catadeleon_128.jpg','Avon','Evansville',81);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (99,'Jesse','Anderson','Santiago Legros','Legacy Intranet Administrator','District','1-725-428-3354 x32961','Gaetano19@hotmail.com','https://cdn.fakercloud.com/avatars/kanickairaj_128.jpg','Borders','East Doraside',3);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (100,'Ashleigh','Homenick','Mr. Russell Gleason','Chief Division Developer','Central','(545) 233-5944 x7453','Maxie.Wyman18@hotmail.com','https://cdn.fakercloud.com/avatars/stan_128.jpg','Avon','Lake Charles',20);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (101,'Leann','Yost','Boyd Dare','Senior Data Strategist','Human','933-475-5625 x89361','Kavon.Gleichner59@yahoo.com','https://cdn.fakercloud.com/avatars/scottfeltham_128.jpg','Avon','Monroe',69);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (102,'Dangelo','Stark','Frederick Pfannerstill DDS','Forward Infrastructure Supervisor','Dynamic','1-327-301-9714 x8640','Kaia_Russel73@gmail.com','https://cdn.fakercloud.com/avatars/adammarsbar_128.jpg','Cambridgeshire','Oceanside',3);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (103,'Nelda','Kshlerin','Irvin MacGyver','Investor Integration Facilitator','Global','1-355-763-8683 x38780','Gertrude_Considine55@hotmail.com','https://cdn.fakercloud.com/avatars/exentrich_128.jpg','Buckinghamshire','Haleighland',37);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (104,'Darius','Russel','Terence Prosacco','Dynamic Usability Representative','Corporate','949.354.1610 x9110','Mohamed.Leuschke68@hotmail.com','https://cdn.fakercloud.com/avatars/ganserene_128.jpg','Borders','West Haven',3);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (105,'Yoshiko','Wisozk','Kim Koss','Global Operations Consultant','Dynamic','713-269-2712 x7438','Victoria_Cremin@hotmail.com','https://cdn.fakercloud.com/avatars/borges_marcos_128.jpg','Bedfordshire','Erie',5);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (106,'Jammie','Fritsch','Bob Kutch','Senior Research Director','Principal','993.855.5695 x8444','Yessenia_Gulgowski@yahoo.com','https://cdn.fakercloud.com/avatars/BroumiYoussef_128.jpg','Bedfordshire','Seattle',41);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (107,'Dayna','Haag','Janie Ratke','Product Program Facilitator','Central','601.642.4211','Ahmed.Carroll0@gmail.com','https://cdn.fakercloud.com/avatars/joelhelin_128.jpg','Cambridgeshire','Port Cathrineview',82);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (108,'Allison','Boyle','Ricardo Schuppe','Principal Identity Developer','Principal','(251) 326-6417 x49999','Dallas22@yahoo.com','https://cdn.fakercloud.com/avatars/joshuasortino_128.jpg','Borders','North Williamberg',91);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (109,'Sydney','Larson','Olga Lowe','Direct Data Engineer','Principal','904-215-6948 x14105','Webster10@gmail.com','https://cdn.fakercloud.com/avatars/klefue_128.jpg','Cambridgeshire','Port Dario',50);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (110,'Violette','Romaguera','Cameron Hegmann','Internal Division Engineer','Central','1-728-238-7182 x681','Ena.Kihn99@yahoo.com','https://cdn.fakercloud.com/avatars/nicklacke_128.jpg','Cambridgeshire','North Jamel',61);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (111,'Barrett','Upton','Phil Rippin','Direct Configuration Architect','Forward','1-263-461-4103 x75237','Gloria_Barton@hotmail.com','https://cdn.fakercloud.com/avatars/kolmarlopez_128.jpg','Avon','New Maureen',72);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (112,'Jordyn','Goodwin','Dennis Heidenreich','Future Data Associate','National','(699) 409-8923 x03078','Presley94@hotmail.com','https://cdn.fakercloud.com/avatars/ashernatali_128.jpg','Berkshire','Port Marieshire',98);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (113,'Alvis','Wyman','Hilda O''Connell','Senior Branding Producer','Future','301.446.8782 x9772','Charley5@yahoo.com','https://cdn.fakercloud.com/avatars/afusinatto_128.jpg','Borders','Port Kirstenfort',88);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (114,'Elijah','Cremin','Marcia Okuneva','Dynamic Solutions Coordinator','Dynamic','(565) 373-0528 x1506','Jude.Pfeffer25@gmail.com','https://cdn.fakercloud.com/avatars/ccinojasso1_128.jpg','Cambridgeshire','West Veldaside',76);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (115,'Deron','Mayer','Molly McDermott','Regional Division Orchestrator','Internal','(655) 321-0037','Stephany_Stark@gmail.com','https://cdn.fakercloud.com/avatars/harry_sistalam_128.jpg','Bedfordshire','Portland',69);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (116,'Emil','Wintheiser','Brooke Muller','Dynamic Communications Agent','Forward','814-607-8903','Shea.Lubowitz42@gmail.com','https://cdn.fakercloud.com/avatars/andrewarrow_128.jpg','Cambridgeshire','South Angusfurt',97);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (117,'Aisha','Schimmel','Daniel Stroman','Central Research Agent','National','612.618.1331 x216','Arlene.Bernhard4@gmail.com','https://cdn.fakercloud.com/avatars/dactrtr_128.jpg','Bedfordshire','Princessbury',94);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (118,'Stella','Moen','Bradley Stoltenberg IV','District Marketing Administrator','Chief','330.602.4135','Lorena_Wiegand80@gmail.com','https://cdn.fakercloud.com/avatars/aislinnkelly_128.jpg','Borders','Kosston',31);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (119,'Jamir','Rempel','Darrin Greenfelder','Investor Functionality Strategist','Global','436.758.5085 x01966','Jordon_Haag@hotmail.com','https://cdn.fakercloud.com/avatars/joki4_128.jpg','Berkshire','Daphneton',79);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (120,'Mozell','O''Conner','Guy Upton','Corporate Integration Officer','District','1-405-380-4237 x7466','Georgette_Gislason@yahoo.com','https://cdn.fakercloud.com/avatars/rachelreveley_128.jpg','Cambridgeshire','Fremont',40);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (121,'Ally','King','Victoria Predovic','Dynamic Solutions Specialist','Dynamic','480-841-5883 x4181','Eldora.Blick@gmail.com','https://cdn.fakercloud.com/avatars/sainraja_128.jpg','Berkshire','Florence-Graham',96);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (122,'Judson','Kohler','Kimberly Heller','Product Mobility Strategist','Principal','(448) 273-9793 x7958','Charles53@hotmail.com','https://cdn.fakercloud.com/avatars/carlfairclough_128.jpg','Buckinghamshire','Lake Maximotown',86);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (123,'Kevon','Johns','Horace Lebsack','Chief Web Planner','Customer','587.610.4532 x718','Caesar.Schoen23@hotmail.com','https://cdn.fakercloud.com/avatars/ricburton_128.jpg','Cambridgeshire','Port Raul',7);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (124,'Jordy','Russel','Kimberly Feest','Regional Communications Agent','Legacy','1-235-218-0434','Jovany.Price@gmail.com','https://cdn.fakercloud.com/avatars/panchajanyag_128.jpg','Cambridgeshire','Jailynhaven',81);
INSERT INTO owners(id,first_name,last_name,full_name,job_title,job_type,phone,email,image,country,city,onboarding_completion) VALUES (125,'Augustine','Hermann','Kristopher Koepp','Forward Web Consultant','Internal','674-666-8570','Earnest38@hotmail.com','https://cdn.fakercloud.com/avatars/damenleeturks_128.jpg','Avon','Leonemouth',48);
